DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
	`id` BIGINT(128) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
	`name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '用户名',
	`password` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '密码',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB